name = input("What's your name?")
print(name + "? The fuck kind of name is that?")
color = input("What's your favorite color? Maybe that'll be better.")
print("Seriously? Out of all the colors you chose " + color + "? Basic biiitchhh.")
subject = input("What's your favorite school subject? Probably some stupid shit.")
print("LMFAOOOO bro you like " + subject + "!? You're such a fucking loser!!")